version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: maing
          config-path: .circleci/continue-config.yml
          mapping: |
            demo/.* project-one true
            mobile-apps/androidApp/.* project-two true
            mobile-apps/iosApp/.* project-three true